'use strict';
const $=id=>document.getElementById(id);
const steps=[['Meet the apparatus','The lamp supplies light. Pondweed releases oxygen during photosynthesis. The ruler measures distance; a water bath helps control temperature.'],['Choose a distance','Move the slider to position the lamp. Use the same lamp and pondweed for every trial. Distance is the variable you change.'],['Allow adjustment','Start a 30-second simulated adjustment period. The plant needs time to adjust after a change in light. This is a prototype timing.'],['Measure for 60 seconds','Start the measurement. Observe bubbles emerging from the cut stem. The counter records each emitted bubble; pausing also freezes experiment time.'],['Record and compare','Record this trial, repeat three times per distance, then try another distance. Compare mean bubbles per minute. Moving further away reduces light intensity.']];
let step=0,distance=20,phase='idle',running=false,time=0,count=0,credit=0,last=0,particles=[],trials={10:[],20:[],30:[],40:[],50:[]},recorded=false;
function rate(d){return 90/(1+(d/20)**2);}
function place(){const x=705-distance*11;$('lamp').setAttribute('transform',`translate(${x} 0)`);$('light').setAttribute('d',`M${x+60} 80L720 155V290L${x+60} 145Z`);$('distanceValue').textContent=distance+' cm';$('intensity').textContent=(1/distance**2).toFixed(5);}
function clearRun(){running=false;phase='idle';time=0;count=0;credit=0;particles=[];recorded=false;$('bubbles').replaceChildren();}
function go(n){clearRun();step=n;render();}
function render(){ $('stepLabel').textContent=`STEP ${step+1} OF 5`;$('stepTitle').textContent=steps[step][0];$('instructions').textContent=steps[step][1];$('back').disabled=step===0;$('next').disabled=step===4;$('next').textContent=step===2?'Skip adjustment':'Next step';$('distance').disabled=running||step===3||step===4;$('run').disabled=!(step===2||step===3)||phase==='done';$('run').textContent=running?'Pause':phase==='adjust'||phase==='measure'?'Resume':step===2?'Start adjustment':'Start measurement';$('record').disabled=phase!=='done'||recorded||trials[distance].length>=3;$('timer').textContent=time.toFixed(1)+' s';$('count').textContent=count;place();}
$('distance').oninput=e=>{distance=Number(e.target.value);clearRun();render();};$('back').onclick=()=>go(step-1);$('next').onclick=()=>go(step+1);$('resetTrial').onclick=()=>go(step===4?2:step);
$('run').onclick=()=>{if(phase==='idle'){phase=step===2?'adjust':'measure';time=0;count=0;credit=0;}running=!running;$('status').textContent=running?(phase==='adjust'?'Adjusting to the light…':'Measurement running.'): 'Paused. Time and bubbles are frozen.';render();};
function drawBubbles(){ $('bubbles').innerHTML=particles.map(p=>`<circle cx="${705+Math.sin(p.age*3+p.seed)*3}" cy="${215-p.age*35}" r="${3+p.seed%2}"/>`).join('');}
function frame(stamp){const dt=Math.min((stamp-last)/1000||0,.1);last=stamp;if(running){const duration=phase==='adjust'?30:60;const advance=Math.min(dt*Number($('speed').value),duration-time);time+=advance;particles.forEach(p=>p.age+=advance);particles=particles.filter(p=>p.age<1.15);if(phase==='measure'){credit+=advance*rate(distance)/60;while(credit>=1){credit-=1;count++;particles.push({age:0,seed:count});}}drawBubbles();if(time>=duration){running=false;if(phase==='adjust'){phase='idle';step=3;time=0;$('status').textContent='Adjustment complete. Start the 60-second measurement.';}else{phase='done';step=4;$('status').textContent='Measurement complete. Record your result below.';}}render();}requestAnimationFrame(frame);}
function results(){ $('rows').innerHTML=Object.entries(trials).map(([d,a])=>`<tr><td>${d} cm</td>${[0,1,2].map(i=>`<td>${a[i]??'—'}</td>`).join('')}<td>${a.length?(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1):'—'}</td></tr>`).join('');let svg='<path d="M50 15V215H420" fill="none" stroke="#879cb0"/>';for(let y=0;y<=80;y+=20)svg+=`<path d="M50 ${215-y*2.3}H420" stroke="#e1e9ef"/><text x="22" y="${220-y*2.3}" font-size="12">${y}</text>`;let descriptions=[];for(const [d,a]of Object.entries(trials)){let x=50+Number(d)*7;svg+=`<text x="${x-7}" y="234" font-size="12">${d}</text>`;if(a.length){const m=a.reduce((x,y)=>x+y)/a.length;svg+=`<circle cx="${x}" cy="${215-m*2.3}" r="5" fill="#177a68"/>`;descriptions.push(`${d} cm: ${m.toFixed(1)} bubbles/min`);}}svg+='<text x="165" y="256" font-size="13">Lamp distance (cm)</text><text x="52" y="12" font-size="12">Mean bubbles / minute</text>';$('graph').innerHTML=svg;$('graphText').textContent=descriptions.join(' · ')||'Record a trial to begin your graph.';$('csv').disabled=!descriptions.length;}
$('record').onclick=()=>{if(phase!=='done'||recorded||trials[distance].length>=3)return;trials[distance].push(count);recorded=true;results();render();$('status').textContent='Result recorded. Restart this trial to repeat, or go Back to choose another distance.';};
$('reset').onclick=()=>{trials={10:[],20:[],30:[],40:[],50:[]};distance=20;$('distance').value=20;$('status').textContent='Experiment reset.';go(0);results();};
$('csv').onclick=()=>{let text='distance_cm,trial_1,trial_2,trial_3,mean_bubbles_per_minute,data_type\n';for(const[d,a]of Object.entries(trials))text+=`${d},${a[0]??''},${a[1]??''},${a[2]??''},${a.length?(a.reduce((x,y)=>x+y)/a.length).toFixed(1):''},simulated\n`;const u=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='photosynthesis-results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('ticks').innerHTML=Array.from({length:6},(_,i)=>`<path d="M${705-i*110} 370v10" stroke="#698399"/><text x="${695-i*110}" y="397">${i*10}</text>`).join('');render();results();requestAnimationFrame(frame);
